version: 2

sources:
  - name: adventureworks
    database: AdventureWorks2014
    schema: Sales
    description: "AdventureWorks Sales schema containing sales-related tables. Expected data latency: 12 hours warning, 24 hours error threshold."
    tables:
      - name: Customer
        description: "Raw customer data from AdventureWorks Sales schema. Expected latency: 12 hours warning, 24 hours error."
        loaded_at_field: ModifiedDate
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
      - name: SalesOrderHeader
        description: "Raw sales order header data from AdventureWorks. Expected latency: 12 hours warning, 24 hours error."
        loaded_at_field: ModifiedDate
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
      - name: SalesOrderDetail
        description: "Raw sales order detail data from AdventureWorks. Expected latency: 12 hours warning, 24 hours error."
        loaded_at_field: ModifiedDate
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

  - name: adventureworks_production
    database: AdventureWorks2014
    schema: Production
    description: "AdventureWorks Production schema containing product-related tables. Expected data latency: 12 hours warning, 24 hours error threshold."
    tables:
      - name: Product
        description: "Raw product data from AdventureWorks. Expected latency: 12 hours warning, 24 hours error."
        loaded_at_field: ModifiedDate
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
      - name: ProductSubcategory
        description: "Raw product subcategory data from AdventureWorks. Expected latency: 12 hours warning, 24 hours error."
        loaded_at_field: ModifiedDate
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
      - name: ProductCategory
        description: "Raw product category data from AdventureWorks. Expected latency: 12 hours warning, 24 hours error."
        loaded_at_field: ModifiedDate
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

  - name: adventureworks_person
    database: AdventureWorks2014
    schema: Person
    description: "AdventureWorks Person schema containing person-related tables. Expected data latency: 12 hours warning, 24 hours error threshold."
    tables:
      - name: Person
        description: "Raw person data from AdventureWorks. Expected latency: 12 hours warning, 24 hours error."
        loaded_at_field: ModifiedDate
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
